site_name: Defence Digital Service
site_description: 'Defence Digital Service'
site_author: 'DDS'
docs_dir: docs/
repo_name: 'defencedigital/'
repo_url: 'https://github.com/defencedigital/defencedigital.github.io'
nav:
    - Home: index.md
theme:
  name: material
  palette:
    scheme: slate

    primary: blue grey
    accent: deep purple
